import type { NewsItem, NewsSourcePlatform, TrackedSource } from '@/types';

export const newsItemsSeed: NewsItem[] = [
  {
    id: 'news-1',
    title: '品牌把短视频预算回流到图文场域，内容团队开始重新争抢“解释权”',
    summary: '本周多家消费品牌开始把部分创意预算从纯短视频投向深度图文，核心原因不是成本，而是图文在复杂议题上的解释效率更高。',
    cover_image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    source_platform: 'x',
    source_url: 'https://x.com/',
    author_name: 'Media Signals',
    published_at: '2026-03-19T09:10:00.000Z',
    ingest_method: 'auto_tracked',
    status: 'featured',
    created_by: 'ops@virax.local',
    updated_by: 'ops@virax.local',
    tags: ['预算转移', '内容策略'],
    is_top_story: true,
    source_metadata: {
      engagement: 18200,
      thread_length: 6,
    },
  },
  {
    id: 'news-2',
    title: '公众号长文重新成为行业周会素材，关键不是阅读量，而是可复用观点密度',
    summary: '内部讨论中，高层更关注文章是否能沉淀观点、支撑判断，而不是单篇是否爆量。这类内容更适合做情报板和复盘资料。',
    cover_image_url: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80',
    source_platform: 'wechat',
    source_url: 'https://mp.weixin.qq.com/',
    author_name: '内容方法论研究室',
    published_at: '2026-03-18T03:30:00.000Z',
    ingest_method: 'manual',
    status: 'featured',
    created_by: 'editor@virax.local',
    updated_by: 'editor@virax.local',
    tags: ['公众号', '团队看板'],
    is_top_story: true,
  },
  {
    id: 'news-3',
    title: 'X 上的行业观察帖开始承担“早盘信号”角色，团队希望每天自动跟踪重点作者',
    summary: '与公众号相比，X 更适合提供第一时间的行业异动和观点分歧，适合作为自动抓取的优先来源。',
    cover_image_url: 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?auto=format&fit=crop&w=1200&q=80',
    source_platform: 'x',
    source_url: 'https://x.com/',
    author_name: 'Growth Dispatch',
    published_at: '2026-03-17T15:50:00.000Z',
    ingest_method: 'auto_tracked',
    status: 'featured',
    created_by: 'system',
    updated_by: 'analyst@virax.local',
    tags: ['自动跟踪', '舆情信号'],
    is_top_story: true,
  },
  {
    id: 'news-4',
    title: '出海团队开始用“图文情报池”替代散落在群里的链接转发',
    summary: '把碎片化链接收敛成统一板块后，会议前的准备效率明显提升，尤其适合跨时区团队。',
    source_platform: 'wechat',
    source_url: 'https://mp.weixin.qq.com/',
    author_name: '品牌出海手记',
    published_at: '2026-03-16T08:20:00.000Z',
    ingest_method: 'manual',
    status: 'featured',
    created_by: 'ops@virax.local',
    updated_by: 'ops@virax.local',
    tags: ['协同流程'],
  },
  {
    id: 'news-5',
    title: '我们关注的三位 X 作者本周都提到“图文比视频更适合记录行业方法论”',
    summary: '相同判断来自不同领域账号，说明这不是单点偏好，而是内容表达方式正在发生偏移。',
    source_platform: 'x',
    source_url: 'https://x.com/',
    author_name: 'Signal Hunter',
    published_at: '2026-03-15T12:00:00.000Z',
    ingest_method: 'auto_tracked',
    status: 'pending',
    created_by: 'system',
    updated_by: 'system',
    tags: ['候选', '观察中'],
  },
  {
    id: 'news-6',
    title: '公众号文章提到“信息密度回归”，但案例较弱，暂不进入首页',
    summary: '论点方向值得跟踪，但当前案例和数据支撑不足，更适合保留在候选池继续观察。',
    source_platform: 'wechat',
    source_url: 'https://mp.weixin.qq.com/',
    author_name: '品牌笔记',
    published_at: '2026-03-14T05:15:00.000Z',
    ingest_method: 'manual',
    status: 'ignored',
    created_by: 'editor@virax.local',
    updated_by: 'editor@virax.local',
    tags: ['待补证据'],
  },
  {
    id: 'news-7',
    title: '热点追踪正在从“内容搬运”转向“判断筛选”，内部编辑角色变得更关键',
    summary: '抓取能力只是入口，真正拉开差距的是筛选标准、摘要能力和信息呈现方式。',
    source_platform: 'x',
    source_url: 'https://x.com/',
    author_name: 'Editorial Ops',
    published_at: '2026-03-13T18:40:00.000Z',
    ingest_method: 'manual',
    status: 'featured',
    created_by: 'ops@virax.local',
    updated_by: 'ops@virax.local',
    tags: ['编辑流', '运营'],
  },
  {
    id: 'news-8',
    title: '团队建议把微信公众号内容作为“深读层”，X 作为“预警层”进行双轨管理',
    summary: '这是目前最适合内部工作台的结构：X 用来发现，公众号用来补充完整观点。',
    source_platform: 'wechat',
    source_url: 'https://mp.weixin.qq.com/',
    author_name: '情报协同备忘录',
    published_at: '2026-03-12T10:10:00.000Z',
    ingest_method: 'manual',
    status: 'pending',
    created_by: 'strategy@virax.local',
    updated_by: 'strategy@virax.local',
    tags: ['产品结构'],
  },
];

export const trackedSourcesSeed: TrackedSource[] = [
  {
    id: 'source-1',
    platform: 'x',
    handle: '@brandarchive',
    display_name: 'Brand Archive',
    status: 'active',
    last_checked_at: '2026-03-20T02:00:00.000Z',
    latest_headline: '连续 3 条帖子都在讨论品牌如何把解释型内容重新搬回图文。',
  },
  {
    id: 'source-2',
    platform: 'x',
    handle: '@signaldesk',
    display_name: 'Signal Desk',
    status: 'active',
    last_checked_at: '2026-03-20T01:30:00.000Z',
    latest_headline: '最新线程聚焦“AI 时代为什么更需要人工整理资讯入口”。',
  },
  {
    id: 'source-3',
    platform: 'x',
    handle: '@marketthread',
    display_name: 'Market Thread',
    status: 'paused',
    last_checked_at: '2026-03-18T23:30:00.000Z',
    latest_headline: '账号暂停跟踪中，等待 API 字段和抓取策略确认。',
  },
];

export function getPlatformLabel(platform: NewsSourcePlatform) {
  return platform === 'x' ? 'X / Twitter' : '微信公众号';
}

export function isWithinDays(isoDate: string, days: number) {
  const now = Date.now();
  const target = new Date(isoDate).getTime();
  const diff = now - target;
  return diff <= days * 24 * 60 * 60 * 1000;
}
